// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.20.3
// source: contracts/k-means.proto

package algorithms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinates []float32 `protobuf:"fixed32,1,rep,packed,name=Coordinates,proto3" json:"Coordinates,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_contracts_k_means_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_k_means_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_contracts_k_means_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetCoordinates() []float32 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type Cluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Centroid *Point   `protobuf:"bytes,1,opt,name=Centroid,proto3" json:"Centroid,omitempty"`
	Points   []*Point `protobuf:"bytes,2,rep,name=Points,proto3" json:"Points,omitempty"`
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_contracts_k_means_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_k_means_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_contracts_k_means_proto_rawDescGZIP(), []int{1}
}

func (x *Cluster) GetCentroid() *Point {
	if x != nil {
		return x.Centroid
	}
	return nil
}

func (x *Cluster) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Kstart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points   []*Point `protobuf:"bytes,1,rep,name=Points,proto3" json:"Points,omitempty"`
	Clasters int64    `protobuf:"varint,2,opt,name=Clasters,proto3" json:"Clasters,omitempty"`
}

func (x *Kstart) Reset() {
	*x = Kstart{}
	mi := &file_contracts_k_means_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kstart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kstart) ProtoMessage() {}

func (x *Kstart) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_k_means_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kstart.ProtoReflect.Descriptor instead.
func (*Kstart) Descriptor() ([]byte, []int) {
	return file_contracts_k_means_proto_rawDescGZIP(), []int{2}
}

func (x *Kstart) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *Kstart) GetClasters() int64 {
	if x != nil {
		return x.Clasters
	}
	return 0
}

type ClusterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clusters []*Cluster `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
}

func (x *ClusterList) Reset() {
	*x = ClusterList{}
	mi := &file_contracts_k_means_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterList) ProtoMessage() {}

func (x *ClusterList) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_k_means_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterList.ProtoReflect.Descriptor instead.
func (*ClusterList) Descriptor() ([]byte, []int) {
	return file_contracts_k_means_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterList) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

var File_contracts_k_means_proto protoreflect.FileDescriptor

var file_contracts_k_means_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x6b, 0x2d, 0x6d, 0x65,
	0x61, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x73, 0x22, 0x29, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x02, 0x52, 0x0b, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x22,
	0x61, 0x0a, 0x07, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x08, 0x43, 0x65,
	0x6e, 0x74, 0x72, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08,
	0x43, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x06, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x22, 0x4e, 0x0a, 0x06, 0x4b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x28, 0x0a, 0x06,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x6c, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x73, 0x22, 0x3d, 0x0a, 0x0b, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x2e, 0x0a, 0x08, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x08, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x73, 0x42, 0x15, 0x5a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6c,
	0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contracts_k_means_proto_rawDescOnce sync.Once
	file_contracts_k_means_proto_rawDescData = file_contracts_k_means_proto_rawDesc
)

func file_contracts_k_means_proto_rawDescGZIP() []byte {
	file_contracts_k_means_proto_rawDescOnce.Do(func() {
		file_contracts_k_means_proto_rawDescData = protoimpl.X.CompressGZIP(file_contracts_k_means_proto_rawDescData)
	})
	return file_contracts_k_means_proto_rawDescData
}

var file_contracts_k_means_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contracts_k_means_proto_goTypes = []any{
	(*Point)(nil),       // 0: contracts.Point
	(*Cluster)(nil),     // 1: contracts.Cluster
	(*Kstart)(nil),      // 2: contracts.Kstart
	(*ClusterList)(nil), // 3: contracts.ClusterList
}
var file_contracts_k_means_proto_depIdxs = []int32{
	0, // 0: contracts.Cluster.Centroid:type_name -> contracts.Point
	0, // 1: contracts.Cluster.Points:type_name -> contracts.Point
	0, // 2: contracts.Kstart.Points:type_name -> contracts.Point
	1, // 3: contracts.ClusterList.clusters:type_name -> contracts.Cluster
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_contracts_k_means_proto_init() }
func file_contracts_k_means_proto_init() {
	if File_contracts_k_means_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contracts_k_means_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_k_means_proto_goTypes,
		DependencyIndexes: file_contracts_k_means_proto_depIdxs,
		MessageInfos:      file_contracts_k_means_proto_msgTypes,
	}.Build()
	File_contracts_k_means_proto = out.File
	file_contracts_k_means_proto_rawDesc = nil
	file_contracts_k_means_proto_goTypes = nil
	file_contracts_k_means_proto_depIdxs = nil
}
