// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: contracts/manager.proto

package algorithms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlgorithmsService_DoAlgorithm_FullMethodName = "/contracts.AlgorithmsService/DoAlgorithm"
)

// AlgorithmsServiceClient is the client API for AlgorithmsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlgorithmsServiceClient interface {
	DoAlgorithm(ctx context.Context, in *Kstart, opts ...grpc.CallOption) (*ClusterList, error)
}

type algorithmsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlgorithmsServiceClient(cc grpc.ClientConnInterface) AlgorithmsServiceClient {
	return &algorithmsServiceClient{cc}
}

func (c *algorithmsServiceClient) DoAlgorithm(ctx context.Context, in *Kstart, opts ...grpc.CallOption) (*ClusterList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterList)
	err := c.cc.Invoke(ctx, AlgorithmsService_DoAlgorithm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlgorithmsServiceServer is the server API for AlgorithmsService service.
// All implementations must embed UnimplementedAlgorithmsServiceServer
// for forward compatibility.
type AlgorithmsServiceServer interface {
	DoAlgorithm(context.Context, *Kstart) (*ClusterList, error)
	mustEmbedUnimplementedAlgorithmsServiceServer()
}

// UnimplementedAlgorithmsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlgorithmsServiceServer struct{}

func (UnimplementedAlgorithmsServiceServer) DoAlgorithm(context.Context, *Kstart) (*ClusterList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoAlgorithm not implemented")
}
func (UnimplementedAlgorithmsServiceServer) mustEmbedUnimplementedAlgorithmsServiceServer() {}
func (UnimplementedAlgorithmsServiceServer) testEmbeddedByValue()                           {}

// UnsafeAlgorithmsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlgorithmsServiceServer will
// result in compilation errors.
type UnsafeAlgorithmsServiceServer interface {
	mustEmbedUnimplementedAlgorithmsServiceServer()
}

func RegisterAlgorithmsServiceServer(s grpc.ServiceRegistrar, srv AlgorithmsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAlgorithmsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlgorithmsService_ServiceDesc, srv)
}

func _AlgorithmsService_DoAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Kstart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmsServiceServer).DoAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlgorithmsService_DoAlgorithm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmsServiceServer).DoAlgorithm(ctx, req.(*Kstart))
	}
	return interceptor(ctx, in, info, handler)
}

// AlgorithmsService_ServiceDesc is the grpc.ServiceDesc for AlgorithmsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlgorithmsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contracts.AlgorithmsService",
	HandlerType: (*AlgorithmsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoAlgorithm",
			Handler:    _AlgorithmsService_DoAlgorithm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/manager.proto",
}
