// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.20.3
// source: contracts/worker.proto

package algorithms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RqData        *Kstart `protobuf:"bytes,1,opt,name=rq_data,json=rqData,proto3" json:"rq_data,omitempty"`
	CorrelationId string  `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
}

func (x *WorkerRq) Reset() {
	*x = WorkerRq{}
	mi := &file_contracts_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRq) ProtoMessage() {}

func (x *WorkerRq) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRq.ProtoReflect.Descriptor instead.
func (*WorkerRq) Descriptor() ([]byte, []int) {
	return file_contracts_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerRq) GetRqData() *Kstart {
	if x != nil {
		return x.RqData
	}
	return nil
}

func (x *WorkerRq) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type WorkerRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RsData        *ClusterList `protobuf:"bytes,1,opt,name=rs_data,json=rsData,proto3" json:"rs_data,omitempty"`
	CorrelationId string       `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
}

func (x *WorkerRs) Reset() {
	*x = WorkerRs{}
	mi := &file_contracts_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRs) ProtoMessage() {}

func (x *WorkerRs) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRs.ProtoReflect.Descriptor instead.
func (*WorkerRs) Descriptor() ([]byte, []int) {
	return file_contracts_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerRs) GetRsData() *ClusterList {
	if x != nil {
		return x.RsData
	}
	return nil
}

func (x *WorkerRs) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_contracts_worker_proto protoreflect.FileDescriptor

var file_contracts_worker_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x73, 0x1a, 0x17, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x6b,
	0x2d, 0x6d, 0x65, 0x61, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x08,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x71, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x71, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x4b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x06, 0x72, 0x71,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f,
	0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x08, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x72, 0x73, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x73, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x06, 0x72, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42,
	0x15, 0x5a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6c, 0x67, 0x6f,
	0x72, 0x69, 0x74, 0x68, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contracts_worker_proto_rawDescOnce sync.Once
	file_contracts_worker_proto_rawDescData = file_contracts_worker_proto_rawDesc
)

func file_contracts_worker_proto_rawDescGZIP() []byte {
	file_contracts_worker_proto_rawDescOnce.Do(func() {
		file_contracts_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_contracts_worker_proto_rawDescData)
	})
	return file_contracts_worker_proto_rawDescData
}

var file_contracts_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_worker_proto_goTypes = []any{
	(*WorkerRq)(nil),    // 0: contracts.WorkerRq
	(*WorkerRs)(nil),    // 1: contracts.WorkerRs
	(*Kstart)(nil),      // 2: contracts.Kstart
	(*ClusterList)(nil), // 3: contracts.ClusterList
}
var file_contracts_worker_proto_depIdxs = []int32{
	2, // 0: contracts.WorkerRq.rq_data:type_name -> contracts.Kstart
	3, // 1: contracts.WorkerRs.rs_data:type_name -> contracts.ClusterList
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contracts_worker_proto_init() }
func file_contracts_worker_proto_init() {
	if File_contracts_worker_proto != nil {
		return
	}
	file_contracts_k_means_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contracts_worker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_worker_proto_goTypes,
		DependencyIndexes: file_contracts_worker_proto_depIdxs,
		MessageInfos:      file_contracts_worker_proto_msgTypes,
	}.Build()
	File_contracts_worker_proto = out.File
	file_contracts_worker_proto_rawDesc = nil
	file_contracts_worker_proto_goTypes = nil
	file_contracts_worker_proto_depIdxs = nil
}
